name: mhgap_urdu
description: "Intervention Guide SUD Module"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+16

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_pdfview: ^1.3.2
  permission_handler: ^10.2.0 
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.3
  pdfx: ^2.6.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  http: ^0.13.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  bloc: ^8.1.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  photo_view: ^0.14.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/files/output_long_page.pdf
    - assets/files/full.pdf
    # - assets/images/logo1.png
    # - assets/images/logo2.png
    # - assets/images/logo3.png
    # - assets/images/logo4.png
    - assets/vectors/assignment_turned_in.png
    - assets/vectors/forward_media.png
    - assets/vectors/chat_info.png
    - assets/vectors/prescriptions.png
    # - assets/images/emergency_assessment.jpg
    # - assets/images/emergency_diagnosis1.png
    # - assets/images/emergency_diagnosis2.png
    # - assets/images/emergency_diagnosis3.png
    # - assets/images/emergency_diagnosis_1.png
    # - assets/images/emergency_diagnosis_2.png
    # - assets/images/emergency_diagnosis_3.png
    # - assets/images/emergency_diagnosis_4.png
    # - assets/images/emergency_diagnosis_5.png
    # - assets/images/emergency_diagnosis_6.png
    # - assets/images/emergency_diagnosis_7.png
    # - assets/images/chart_page-0001.jpg
    # - assets/images/chart_page-0002.jpg
    # - assets/images/chart_page-0003.jpg
    # - assets/images/chart_page-0004.jpg
    # - assets/images/chart_page-0005.jpg
    # - assets/images/chart_page-0006.jpg
    # - assets/images/chart2.png
    - assets/images/assessment_icon.png
    - assets/images/description_icon.png
    - assets/images/management_icon.png
    - assets/images/followup_icon.png
    - assets/images/further_information.png
    - assets/images/logo1.png
    - assets/images/logo2.png
    - assets/images/logo3.png
    - assets/images/logo4.png
    - assets/images/splash_screen.png
    - assets/images/home.png
    - assets/images/tutorial1.png
    - assets/images/tutorial2.png
    - assets/images/tutorial3.png
    - assets/images/tutorial4.png
    - assets/images/tutorial5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nastaliq
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Medium.ttf

    - family: Jameel
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeqKasheeda.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"